[package]
name = "aoc-2025-1"
version = "0.1.0"
edition = "2024"

[dependencies]
indoc = "2.0.7"
reqwest = { version = "0.12.24", features = ["blocking"] }
substring = "1.4.5"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
